
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form action="" method="post">
        <fieldset>
            <legend>Connexion</legend>
            <?php if (isset($msg_error)) : ?>
                <span style="color:red;"><?= $msg_error ?></span>
            <?php endif ?>
            <p>
            <label for="login">Identifiant:</label></p>
            <input type="text" id="login" name="login" />
            <p>
            <label for="pwd">Mot de passe:</label></p>
            <input type="password" id="pwd" name="pwd" />
            <br>
            <button type="submit" name="bouton">Envoyer</button>
        </fieldset>
    </form>
</body>
</html>